### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by kuanb** [jorahn/python2-hdf5#1]
Just wanted to note a small issue with the README. The first line of code in [this section](https://github.com/jorahn/python2-hdf5#build-on-top-of-this-image-with-a-dockerfile-like-this) includes a type. Should change: `FROM rcsa/python2-hfd5:latest` to `FROM rcsa/python2-hdf5:latest`. The "f" and the "d" are transposed.

Thanks for the resource, by the way.

**Comment by jorahn** [comment]
thanks for the hint, should be fixed with https://github.com/jorahn/python2-hdf5/commit/32dfebcf2f7f378887b7039f0e041d9291f65d15
